name: Run tests

on:
  - push
  - workflow_dispatch

env:
  SOURCE_CODE_DIR: src

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 $SOURCE_CODE_DIR --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 $SOURCE_CODE_DIR --count --exit-zero --statistics
      - name: Security check with bandit
        run: |
          bandit -r $SOURCE_CODE_DIR

  test:
    needs: [lint]
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # - name: Test with pytest
      #   run: |
      #     pytest $SOURCE_CODE_DIR
